loader_cfg:
  data_path: '/data/ohe_5utr_95_64to256_PRI.pt'
  batch: 64
  train_prop: 0.9
  shuffle: true
  seed: 2024

logger_cfg:
  save_flag: True
  log_flag: True
  save_model_epochs: 100 
  save_path: '/saved_models/5utr/vae/'
  logger_project: "utr5-VAE-256"
  logger_runname: "VAE-batch64-maxpool2_1-init-latent8-PRI"
  logger_note: ''
  # resume run
  resume_flag: False
  resume_TIME: ""
  resume_runid: ""
  resume_epoch: 0

trainer_cfg:
  epoch: 2000
  lr: 1e-4
  optimizer: "Adam"
#  lr_warmup_steps: 500

# for max length 256
model_cfg:
  check_point: ""
  in_channel: 5
  seq2img_num_layers: 4
  seq2img_num_feature_layers: 1
  seq2img_img_channels: 128
  hidden_width: [2, 4, 8, 16]
  beta_flag: False
  kld_weight: 0.000001
