loader_cfg:
  data_path: '/data/ohe_5utr_95_64to256.pt'
  batch: 64
  train_prop: 0.9
  shuffle: true
  seed: 2024

logger_cfg:
  save_flag: True
  log_flag: True
  save_model_epochs: 100 
  save_path: '/saved_models/5utr/vae/'
  logger_project: "mRNA_diff-5utr-vae-256"
  logger_runname: "VAE-256"
  logger_note: '256version-VAE'

trainer_cfg:
  epoch: 1000
  lr: 0.0001
  optimizer: "Adam"
#  lr_warmup_steps: 500

# for max length 256
model_cfg:
  check_point: ""
  in_channel: 5
  seq2img_num_layers: 4
  seq2img_num_feature_layers: 1
  seq2img_img_channels: 128
  hidden_width: [2, 4, 8, 16]
  beta_flag: False
  kld_weight: 0.000001
  