loader_cfg:
  data_path: '/data/ohe_5utr_95_64to256.pt'
  batch: 64
  train_prop: 0.9
  shuffle: true
  seed: 2024

logger_cfg:
  save_flag: True
  log_flag: True
  save_model_epochs: 100 
  save_path: '/saved_models/5utr/vae/'
  logger_project: "mRNA_diff-5utr-vae-256"
  logger_runname: "VAE-maxpool-middle"
  logger_note: '256version-VAE maxpool layer at middle of encoder, encode:1, decode:2'
  # resume run
  resume_flag: False
  resume_TIME: "2024-09-26_16-09-48"
  resume_runid: "3n8su226"
  resume_epoch: 1000


trainer_cfg:
  epoch: 1500
  lr: 1e-4
  optimizer: "Adam"
#  lr_warmup_steps: 500

# for max length 256
model_cfg:
  check_point: "/saved_models/5utr/vae/2024-09-26_16-09-48_final_utr5vae.pt"
  in_channel: 5
  seq2img_num_layers: 4
  seq2img_num_feature_layers: 1
  seq2img_img_channels: 128
  hidden_width: [2, 4, 8, 16]
  beta_flag: False
  kld_weight: 0.000001
