generate_cfg:
  save_flag: True
  save_path: '/generation/5utr/PRI_256.fasta'
  timesteps: 1000
  total_samples: 2048
  batch_size: 1000


vae_cfg:
  vae_path: "/saved_models/5utr/vae/2024-10-10_22-34-04_best_utr5vae.pt"
  in_channel: 5
  seq2img_num_layers: 4
  seq2img_num_feature_layers: 1
  seq2img_img_channels: 128
  hidden_width: [8, 16, 32]
  beta_flag: False
  kld_weight: 0.000001

diffusion_cfg:
  diffusion_path: "/saved_models/5utr/unet/2024-10-11_14-53-57_best_unet2d.pt"
  scheduler: "DDPM"
  timesteps: 1000
  # model parameters
  # latent: [16, 16, 16] or [8, 8, 8]
  sample_size: 16  # 16 latent size / 8 latent size 
  in_channels: 16
  out_channels: 16
  block_out_channels: [256, 256, 512, 512]  # 4 blocks each side
  down_block_types: ["DownBlock2D", "DownBlock2D", "AttnDownBlock2D", "DownBlock2D"]
  up_block_types: ["UpBlock2D", "AttnUpBlock2D", "UpBlock2D", "UpBlock2D"]
  layers_per_block: 8