generate_cfg:
  gen_seqs_path: "5utr/"
  gen_model_path: "5utr/2024-08-27_14-46-46_final_unet_model.pt"
  gen_num: 2048
  gen_batch_size: 512

loader_cfg:
  data_name: 'ohe_5utr_95_64to128.pt'
  batch: 64
  train_prop: 0.8
  shuffle: true
  seed: 2024

logger_cfg:
  save_flag: true
  save_model_epochs: 10 
  save_path: '/save_models/5utr/'

trainer_cfg:
  epoch: 100 
  lr: 1e-5
  lr_warmup_steps: 5000
  optimizer: "AdamW"

model_cfg:
  scheduler: "DDPM"
  num_train_timesteps: 1000
  input_length: 128
  in_channels: 5
  out_channels: 5
  layers_per_block: 4
  block_out_channels: [256, 256, 512, 512]  # 4 blocks each side
  down_block_types: ["DownBlock1D", "DownBlock1D", "AttnDownBlock1D", "DownBlock1D"]
  up_block_types: ["UpBlock1D", "AttnUpBlock1D", "UpBlock1D", "UpBlock1D"]

